trigger:
- main

pool:
  vmImage: ubuntu-latest

variables: 
  dockerHubServiceConnection: 'DockerServiceConnection'
  imageName: 'okrx/testing'
#  containerAppName: 
#  resourceGroupName: 
#  containerRegistry: 
#  containerRegistryPassword:  

steps:
  - task: Docker@2
    displayName: "Build Docker Image"
    inputs: 
      command: build
      Dockerfile: '**/Dockerfile'
      tags: | 
        $(imagename):$(Build.BuildId)

  - task: Docker@2
    displayName: 'Push Docker image to DuckerHub'
    inputs:
      command: push
      repository: $(imageName)
      tags: |
        $(Build.BuildId)
      containerRegistry: $(dockerHubServiceConnection)  