trigger:
- main

pool:
  vmImage: ubuntu-latest

variables: 
  dockerHubServiceConnection: 'DockerServiceConnection'
  azureServiceConnection: 'AzureServiceConnection'
  imageName: 'okrx/testing'
  containerAppName: 'app01'
  resourceGroupName: 'rg-pokroy-tf-demo-01'
  containerRegistry: 'okrx'
# containerRegistryPassword:  

steps:
  - task: Docker@2
    displayName: "Login to DockerHub"
    inputs: 
      command: login
      containerRegistry: $(dockerHubServiceConnection)

  - task: Docker@2
    displayName: "Build and Push Docker Image"
    inputs: 
      command: buildandPush
      Dockerfile: '**/Dockerfile'
      repository: 'okrx/testing'
      tags: | 
        $(Build.BuildId)
  
        
  - task: AzureCLI@2
    displayName: 'Deploy to Azure Container Apps'
    inputs:
      azureSubscription: 'AzureServiceConnection'  # Azure service connection name
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az containerapp create \
          --name $(containerAppName) \
          --resource-group $(resourceGroupName) \
          --image $(containerRegistry)/$(imageName):$(Build.BuildId) \
          --cpu 0.25 \
          --memory 0.5 \
          --ingress 'external' \
          --registry-server index.docker.io \
          --registry-username $(containerRegistry) \
          --registry-password $(containerRegistryPassword)


