trigger:
- none

pool:
  vmImage: ubuntu-latest

variables: 
  dockerHubServiceConnection: 'DockerServiceConnection'
  azureServiceConnection: 'AzureServiceConnection'
  imageName: 'okrx/testing'
  containerAppName: 'app01'
  resourceGroupName: 'rg-pokroy-tf-demo-01'
#  containerRegistry: 
#  containerRegistryPassword:  

steps:
  - task: Docker@2
    displayName: "Login to DockerHub"
    inputs: 
      command: login
      containerRegistry: $(dockerHubServiceConnection)

  - task: Docker@2
    displayName: "Build and Push Docker Image"
    inputs: 
      command: buildandPush
      Dockerfile: '**/Dockerfile'
      repository: 'okrx/testing'
      tags: | 
        $(Build.BuildId)
  
        
  - task: AzureContainerApps@1
    displayName: 'Deploy to Azure Container Apps'
    inputs:
      azureSubscription: $(azureServiceConnection) # Azure Service Connection Name
      appName: $(containerAppName) # Azure Container App name
      resourceGroupName: $(resourceGroupName) # Azure Resource Group
      image: $(imageName):$(Build.BuildId) # Docker image with tag
      registryServer:  $(dockerHubServiceConnection)
      containerAppEnvironment: 'containerappenv'
