trigger:
- main

pool:
  vmImage: ubuntu-latest

variables: 
  dockerHubServiceConnection: 'DockerServiceConnection'
  imageName: 'okrx/testing'
#  containerAppName: 
#  resourceGroupName: 
#  containerRegistry: 
#  containerRegistryPassword:  

steps:
  - task: Docker@2
    displayName: "Login to DockerHub"
    inputs: 
      command: login
      containerRegistry: $(dockerHubServiceConnection)

  - task: Docker@2
    displayName: "Build and Push Docker Image"
    inputs: 
      command: buildandPush
      Dockerfile: '**/Dockerfile'
      repository: 'okrx/testing'
      tags: | 
        $(imageName):$(Build.BuildId)